// <auto-generated />
using System;
using EonWatchesAPI.DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EonWatchesAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EonWatchesAPI.DbContext.Ad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Archived")
                        .HasColumnType("bit");

                    b.Property<string>("Brand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GroupId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAnSeller")
                        .HasColumnType("bit");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ReferenceNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Ads");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Archived = false,
                            Brand = "Omega",
                            CreatedAt = new DateTime(2025, 1, 15, 10, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "USD",
                            GroupId = "G001",
                            IsAnSeller = true,
                            Model = "Speedmaster",
                            Price = 5999.99m,
                            ReferenceNumber = "311.30.42.30.01.005"
                        },
                        new
                        {
                            Id = 2,
                            Archived = false,
                            Brand = "Rolex",
                            CreatedAt = new DateTime(2025, 2, 20, 12, 30, 0, 0, DateTimeKind.Utc),
                            Currency = "USD",
                            GroupId = "G002",
                            IsAnSeller = false,
                            Model = "Submariner",
                            Price = 8999.50m,
                            ReferenceNumber = "124060"
                        },
                        new
                        {
                            Id = 3,
                            Archived = true,
                            Brand = "Seiko",
                            CreatedAt = new DateTime(2024, 12, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "EUR",
                            GroupId = "G003",
                            IsAnSeller = true,
                            Model = "Prospex",
                            Price = 450.00m,
                            ReferenceNumber = "SRPD21"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
