// <auto-generated />
using System;
using EonWatchesAPI.DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EonWatchesAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EonWatchesAPI.DbContext.Ad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Archived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("BatchCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Brand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Caliber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CaseDiameter")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Condition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Currency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("FullSet")
                        .HasColumnType("bit");

                    b.Property<string>("GroupId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsAnSeller")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MessageId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Movement")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Other")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ReferenceNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Shipping")
                        .HasColumnType("bit");

                    b.Property<int?>("TraderId")
                        .HasColumnType("int");

                    b.Property<string>("TraderName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Video")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YearOfManufacture")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("TraderId");

                    b.ToTable("Ads");

                    b.HasData(
                        new
                        {
                            Id = 3,
                            Archived = false,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GroupId = "120363420163603590@g.us",
                            Price = 122m,
                            ReferenceNumber = "123",
                            TraderId = 2
                        },
                        new
                        {
                            Id = 4,
                            Archived = false,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GroupId = "120363420163603590@g.us",
                            Price = 11m,
                            ReferenceNumber = "1234"
                        },
                        new
                        {
                            Id = 5,
                            Archived = false,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GroupId = "120363416829988594@g.us",
                            Price = 500m,
                            ReferenceNumber = "5678",
                            TraderId = 1
                        });
                });

            modelBuilder.Entity("EonWatchesAPI.DbContext.Trader", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("WhapiBearerToken")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.ToTable("Traders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Thomas Van Otterloo",
                            PhoneNumber = "31612231577"
                        },
                        new
                        {
                            Id = 2,
                            Email = "demoaccwatches@gmail.com",
                            Name = "ThomasFake",
                            PhoneNumber = "31619348878"
                        });
                });

            modelBuilder.Entity("EonWatchesAPI.DbContext.Trigger", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReferenceNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TraderId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TraderId");

                    b.ToTable("Triggers");
                });

            modelBuilder.Entity("EonWatchesAPI.DbContext.WhitelistedGroup", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("GroupName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WhitelistedGroups");

                    b.HasData(
                        new
                        {
                            Id = "120363416829988594@g.us",
                            GroupName = "Marktplaats"
                        },
                        new
                        {
                            Id = "120363420163603590@g.us",
                            GroupName = "CoolTraders Only! And god.."
                        });
                });

            modelBuilder.Entity("EonWatchesAPI.Domain.TraderWhitelistedGroup", b =>
                {
                    b.Property<int>("TraderId")
                        .HasColumnType("int");

                    b.Property<string>("GroupId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("TraderId", "GroupId");

                    b.HasIndex("GroupId");

                    b.ToTable("TraderWhitelistedGroups");

                    b.HasData(
                        new
                        {
                            TraderId = 2,
                            GroupId = "120363416829988594@g.us"
                        },
                        new
                        {
                            TraderId = 2,
                            GroupId = "120363420163603590@g.us"
                        },
                        new
                        {
                            TraderId = 1,
                            GroupId = "120363420163603590@g.us"
                        });
                });

            modelBuilder.Entity("EonWatchesAPI.DbContext.Ad", b =>
                {
                    b.HasOne("EonWatchesAPI.DbContext.WhitelistedGroup", "Group")
                        .WithMany("Ads")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EonWatchesAPI.DbContext.Trader", "Trader")
                        .WithMany("Ads")
                        .HasForeignKey("TraderId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Group");

                    b.Navigation("Trader");
                });

            modelBuilder.Entity("EonWatchesAPI.DbContext.Trigger", b =>
                {
                    b.HasOne("EonWatchesAPI.DbContext.Trader", "Trader")
                        .WithMany()
                        .HasForeignKey("TraderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trader");
                });

            modelBuilder.Entity("EonWatchesAPI.Domain.TraderWhitelistedGroup", b =>
                {
                    b.HasOne("EonWatchesAPI.DbContext.WhitelistedGroup", "Group")
                        .WithMany("TraderWhitelistedGroups")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EonWatchesAPI.DbContext.Trader", "Trader")
                        .WithMany("TraderWhitelistedGroups")
                        .HasForeignKey("TraderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Trader");
                });

            modelBuilder.Entity("EonWatchesAPI.DbContext.Trader", b =>
                {
                    b.Navigation("Ads");

                    b.Navigation("TraderWhitelistedGroups");
                });

            modelBuilder.Entity("EonWatchesAPI.DbContext.WhitelistedGroup", b =>
                {
                    b.Navigation("Ads");

                    b.Navigation("TraderWhitelistedGroups");
                });
#pragma warning restore 612, 618
        }
    }
}
