# .github/workflows/ci-sonar-coverage.yml
name: Build, Test & SonarCloud Analyze

on:
  push:
    branches:
      - main

jobs:
  build-and-analyze:
    name: Build, Test & SonarCloud (EonWatchesAPI)
    runs-on: ubuntu-latest            # ← use Ubuntu so "mkdir -p" works

    steps:
      # 1) Check out the repo
      - uses: actions/checkout@v4

      # 2) Install .NET 8 SDK
      - name: Set up .NET 8 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      # 3) Install SonarCloud Scanner
      - name: Install SonarCloud scanner
        run: dotnet tool install --global dotnet-sonarscanner

      # 4) Begin SonarCloud analysis (single line, no backslashes)
      - name: Begin SonarCloud analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          dotnet-sonarscanner begin \
            /k:"ThomasvanOtterloo_Afstudeerstage_2TCI" \
            /o:"mysonarcloudtester" \
            /d:sonar.login="${{ secrets.SONAR_TOKEN }}" \
            /d:sonar.sources="EonWatchesAPI" \
            /d:sonar.cs.opencover.reportsPaths="coverage/OpenCover.xml" \
            /d:sonar.scanner.scanAll=false

      # 5) Restore all projects
      - name: Restore dependencies
        run: dotnet restore

      # 6) Build the solution (so tests can run)
      - name: Build solution
        run: dotnet build EonWatchesAPI.sln --configuration Release

      # 7) Run tests AND generate an OpenCover-format coverage file
      - name: Run tests and collect coverage
        run: |
          mkdir -p coverage
          dotnet test EonWatchesAPI.sln \
            --configuration Release \
            /p:CollectCoverage=true \
            /p:CoverletOutputFormat=opencover \
            /p:CoverletOutput="$(pwd)/coverage/OpenCover.xml"

 # 7.5) Debug coverage output (check if file was generated)
      - name: Debug coverage output
        run: |
          echo "== Listing contents of coverage folder =="
          ls -l coverage
          echo "== First 20 lines of coverage/OpenCover.xml =="
          head -n 20 coverage/OpenCover.xml || echo "coverage/OpenCover.xml not found"


      # 8) End SonarCloud analysis (imports coverage data)
      - name: End SonarCloud analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: dotnet-sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
