name: Build and SonarCloud Analyze (EonWatchesAPI only)

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build & SonarCloud (EonWatchesAPI)
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET 8 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Install SonarCloud scanner
        run: dotnet tool install --global dotnet-sonarscanner

      # ───────────────────────────────────────────────────────────────────
      # Option A (recommended): Put everything on one line (no backslashes)
      # ───────────────────────────────────────────────────────────────────
      - name: Begin SonarCloud analysis (EonWatchesAPI only)
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: dotnet-sonarscanner begin /k:"ThomasvanOtterloo_Afstudeerstage_2TCI" /o:"mysonarcloudtester" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.sources="EonWatchesAPI"

      # ───────────────────────────────────────────────────────────────────
      # Option B (alternate): Use PowerShell backticks (`) for line-continuation
      # (Uncomment this block if you’d rather keep each switch on its own line.)
      # ───────────────────────────────────────────────────────────────────
      # - name: Begin SonarCloud analysis (EonWatchesAPI only)
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      #   run: |
      #     dotnet-sonarscanner begin `
      #       /k:"ThomasvanOtterloo_Afstudeerstage_2TCI" `
      #       /o:"mysonarcloudtester" `
      #       /d:sonar.login="${{ secrets.SONAR_TOKEN }}" `
      #       /d:sonar.sources="EonWatchesAPI"

      - name: Build EonWatchesAPI project
        run: dotnet build EonWatchesAPI/EonWatchesAPI.csproj --configuration Release

      - name: End SonarCloud analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: dotnet-sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
