name: Run MyApiTests

on:
  push:
    branches:
      - main

jobs:
  test:
    name: dotnet 8 Unit Tests
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET 8 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore all projects
        run: dotnet restore

      - name: Build solution
        run: dotnet build --configuration Release

      - name: Run MyApiTests
        # Either put it all on one line:
        run: dotnet test src/MyApiTests/MyApiTests.csproj --configuration Release --verbosity normal

        # Or, if you want it broken up over multiple lines for readability:
        # run: |
        #   dotnet test src/MyApiTests/MyApiTests.csproj \
        #     --configuration Release \
        #     --verbosity normal
